#!/usr/bin/env zsh

# Extracts any archive(s) (if unp isn't installed)
extract() {
	for archive in "$@"; do
		if [ -f "$archive" ]; then
			case $archive in
			*.tar.bz2) tar xvjf $archive ;;
			*.tar.gz) tar xvzf $archive ;;
			*.bz2) bunzip2 $archive ;;
			*.rar) rar x $archive ;;
			*.gz) gunzip $archive ;;
			*.tar) tar xvf $archive ;;
			*.tbz2) tar xvjf $archive ;;
			*.tgz) tar xvzf $archive ;;
			*.zip) unzip $archive ;;
			*.Z) uncompress $archive ;;
			*.7z) 7z x $archive ;;
			*) echo "don't know how to extract '$archive'..." ;;
			esac
		else
			echo "'$archive' is not a valid file!"
		fi
	done
}

# Copy file with a progress bar
cpp() {
    set -e
    strace -q -ewrite cp -- "${1}" "${2}" 2>&1 |
    awk '{
        count += $NF
        if (count % 10 == 0) {
            percent = count / total_size * 100
            printf "%3d%% [", percent
            for (i=0;i<=percent;i++)
                printf "="
            printf ">"
            for (i=percent;i<100;i++)
                printf " "
            printf "]\r"
        }
    }
    END { print "" }' total_size="$(stat -c '%s' "${1}")" count=0
}

# IP address lookup
function whatsmyip () {
    # Internal IP Lookup.
    if command -v ip &> /dev/null; then
        echo -n "Internal IP: "
        ip addr show wlan0 | grep "inet " | awk '{print $2}' | cut -d/ -f1
    else
        echo -n "Internal IP: "
        ifconfig wlan0 | grep "inet " | awk '{print $2}'
    fi

    # External IP Lookup
    echo -n "External IP: "
    curl ip.wtf
}
alias whatismyip="whatsmyip"

ipinfo() {
DASH="$(for i in {1..29}; do echo -n "-"; done)"
for x in "$@"; do echo; echo -e "GEO-IP INFO: ($x)\n"$DASH"";
  curl -s ipinfo.io/$x | sed 's/,\"/\n\"/g' | awk -F\" '/[a-z]/ {printf "%8s : %s\n",$2,$4}';
done; echo
}

# List all system applications
list-packages() {
	case "$1" in
		all|"")
			echo "== Pacman (explicit) =="
			pacman -Qe

			echo -e "\n== AUR =="
			pacman -Qm

			echo -e "\n== Flatpak Apps =="
			flatpak list --app
			;;
		pacman)
			pacman -Qe
			;;
		aur)
			pacman -Qm
			;;
		flatpak)
			flatpak list --app
			;;
		*)
			echo "Usage: list-packages [all|pacman|aur|flatpak]"
			return 1
			;;
	esac
}
