---
- name: Arch Linux System Update
  gather_facts: false
  hosts: localhost
  become: true
  tasks:
    - name: Update package list
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: Update AUR packages
      become: true
      become_user: "aur_builder"
      community.general.pacman:
        upgrade: true
        executable: yay
