# Color Scheme
theme = "Monokai Pro Spectrum"

# Font
font-family = "JetBrainsMono Nerd Font"

# Transparency
background-opacity = 0.8

# Terminal Configs
copy-on-select = "clipboard"
gtk-tabs-location = "hidden"
gtk-titlebar = true
