"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
palette = 'starship'
scan_timeout = 10

format = """
[╭╴](fg:gray)\
$os\
$directory\
[](fg:primary_950 bg:primary_700)\
$git_branch\
$git_commit\
[](fg:primary_700 bg:primary_950)\
$bun\
$nodejs\
$dart\
$golang\
$rust\
$lua\
$terraform\
[](fg:primary_950 bg:primary_950)\
[ ](fg:primary_950)\
$fill\
[ ](fg:primary_950)\
$shell\
$cmd_duration\
$status\
[](fg:primary_700)\
[](fg:gray)[ ]()
[╰╴❯](fg:gray)[ ]()"""

[line_break]
disabled = true

[fill]
style = 'gray'
symbol = '─'

[os]
disabled = false
style = 'bg:primary_700 fg:white'
format = '[](primary_700)[ ]($style)[](fg:primary_700 bg:primary_950)'

[directory]
truncation_length = 1
style = 'bold bg:primary_950 fg:white'
format = '[$path]($style)'
truncation_symbol = "   ~/.../"
repo_root_style = 'bold bg:primary_950 fg:white'
repo_root_format = '[  $repo_root ]($style)'

[directory.substitutions]
"~/Documents" = "󰈙 "
"~/Downloads" = " "
"~/Music" = " "
"~/Pictures" = " "
"~/Videos" = " "
"~/project" = "󱌢 "
"~/GitHub" = " "
"~/.config" = " "
"~/" = " 󰣇 ~ "
"~" = " 󰣇 ~ "

[git_branch]
symbol = ""
style = "bold fg:success_400 bg:primary_700"
format = '[ $symbol $branch(:$remote_branch) ]($style)'

[git_commit]
tag_disabled = true
only_detached = false
style = 'bold fg:white bg:primary_700'
commit_hash_length = 4
format = '[$hash]($style)'

[bun]
symbol = ''
style = "bold fg:white bg:primary_950"
version_format = "v${major}.${minor}"
format = '[ $symbol $version]($style)'

[dart]
symbol = ''
style = "bold fg:primary_300 bg:primary_950"
version_format = "v${major}.${minor}"
format = '[ $symbol $version]($style)'

[golang]
symbol = ""
style = "bold fg:primary_300 bg:primary_950"
version_format = "v${major}.${minor}"
format = '[ $symbol $version]($style)'

[lua]
symbol = ""
style = "bold fg:#c084fc bg:primary_950"
version_format = "v${major}.${minor}"
format = '[ $symbol $version]($style)'

[rust]
symbol = ""
style = "bold fg:#fb923c bg:primary_950"
version_format = "v${major}.${minor}"
format = '[ $symbol $version]($style)'

[terraform]
symbol = ""
style = "bold fg:#c084fc bg:primary_950"
version_format = "v${major}.${minor}"
format = '[ $symbol $version]($style)'

[nodejs]
symbol = ""
style = "bold fg:#4ade80 bg:primary_950"
version_format = "v${major}.${minor}"
format = '[ $symbol $version]($style)'
detect_extensions = [ ]

[status]
disabled = false
style = 'bold bg:primary_950 fg:white'
success_symbol = "[  ](fg:success_400 bg:primary_700)"
symbol = "[  ](fg:danger_500 bg:primary_700)"
format = '[](fg:primary_700 bg:primary_950)[$symbol]($style)'

[cmd_duration]
min_time = 0
show_milliseconds = true
format = "[ $duration ](fg:white bg:primary_950)"

[palettes.starship]
primary_950 = '#192152'
primary_800 = '#2337aa'
primary_700 = '#2442d1'
primary_600 = '#3059e4'
primary_500 = '#4275ef'
primary_300 = '#97bdf9'

success_400 = '#4ADE80'

danger_500 = '#EF4444'

white = '#F9FAFB'
gray = '#9CA3AF'
